### ISSUE TITLE
[Bug] Admin Dashboard logo background 

### ISSUE THREAD

**Issue by Satish-Ghode** [ShwetaKadam21082001/Admin-Dashboard#1]
**Describe the bug** 
The logo Background is gray in light mode . 

**Expected behavior**
the logo background color it should be match light mode .
logo background color : fff ; 

**Screenshots**
![image](https://github.com/ShwetaKadam21082001/Admin-Dashboard/assets/88142229/0008bf76-151c-4cb1-83f9-feb5d3b5d7b7)

**Desktop (please complete the following information):**
 - OS: All
 - Browser : All

**Comment by MohitKambli** [comment]
Hello,
Hope you're doing well.
Is this how you want the logo background to look like?

![image](https://github.com/ShwetaKadam21082001/Admin-Dashboard/assets/31406633/415aac3d-0166-4a78-97d1-d684223c3dde)

This is how the page looks when the dark mode is enabled:

![image](https://github.com/ShwetaKadam21082001/Admin-Dashboard/assets/31406633/dd5f012a-332a-4e9b-b859-3a13e0480828)

In order to achieve such behaviour, I simply made changes in the css file. The code changes look something like this:

```
aside{
    height: 100vh;
    background: white;
}
```

If at all there is something that I misunderstood, then do let me know.
Sincere apologies for causing any trouble just in case.
If you think there are some changes required, then please inform me.

Thanks and Regards,
Mohit Kambli

**Comment by Satish-Ghode** [comment]
@MohitKambli #2  are you able to reproduce the error/bug ?

**Comment by MohitKambli** [comment]
Hello @Satishghode,
Yes, I was able to see the logo's background color to be grey in color.
Once I made the above changes, the logo's background color changed to white.

Thanks and Regards,
Mohit Kambli

**Comment by ShwetaDevv** [comment]
Thank you for contribute thise project
